class Sipctl < Formula
  desc "CLI context router for AI agents — sip from the firehose"
  homepage "https://github.com/vyshnavsdeepak/sipctl"
  version "0.0.0"
  license "MIT"

  # This file is auto-generated by CI. Edit sipctl.rb.tmpl instead.
  on_macos do
    on_arm do
      url "https://github.com/vyshnavsdeepak/sipctl/releases/download/v0.0.0/sip-darwin-arm64"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_intel do
      url "https://github.com/vyshnavsdeepak/sipctl/releases/download/v0.0.0/sip-darwin-x64"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/vyshnavsdeepak/sipctl/releases/download/v0.0.0/sip-linux-arm64"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_intel do
      url "https://github.com/vyshnavsdeepak/sipctl/releases/download/v0.0.0/sip-linux-x64"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  def install
    bin.install Dir["sip-*"].first => "sip"
  end

  test do
    assert_match "", shell_output("echo '' | #{bin}/sip 2>&1 || true")
  end
end
